### ISSUE TITLE
How to retrieve and show all data from localstorage

### ISSUE THREAD

**Issue by indrolie** [indrolie/address-book#1]
My current code only allow me to show 1 set of data at once.
I want to show all of it and make it a list.

https://github.com/indrolie/address-book/blob/e511174db0d87ebd5c449ade70b37796eabfb056/index.js#L41-L55

**Comment by mhaidarhanif** [comment]
Avoid single use of `.innerHTML` to fill the element with the data.

You have to create multiple elements.

**Comment by mhaidarhanif** [comment]
Check this PR https://github.com/indrolie/address-book/pull/2
